
sa_users_db:
  image: mysql
  ports:
    - "3308:3308"
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_PASSWORD: 1234
    MYSQL_DATABASE: users
authentication-ms:
  build: .
  ports:
   - "4044:4044"
  
